# Generated by Django 5.0.2 on 2024-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('entertainment', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
