# Generated by Django 5.0.2 on 2024-04-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_interest_user_delete_user_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
