# Generated by Django 5.0.2 on 2024-04-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_interest_checking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='checking',
        ),
    ]
