# Generated by Django 5.0.2 on 2024-04-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_interest_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
